name: Build openNDS 10.3.0-r1 for OpenWrt 24.10.0 x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          rsync unzip zlib1g-dev file wget libelf-dev libtool tar xz-utils zstd \
          python3-venv python3-setuptools python3-pip

    - name: Download and extract OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/24.10.0/targets/x86/64/openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xf openwrt-sdk-*.tar.zst --one-top-level=openwrt-sdk

    - name: Copy openNDS package
      run: |
        mkdir -p openwrt-sdk/package/network/services/opennds
        cp -r opennds/* openwrt-sdk/package/network/services/opennds/

    - name: Add default UCI config
      run: |
        mkdir -p openwrt-sdk/package/network/services/opennds/files/etc/uci-defaults
        cp files/etc/uci-defaults/99-opennds-default openwrt-sdk/package/network/services/opennds/files/etc/uci-defaults/

    - name: Prepare .config
      run: |
        cd openwrt-sdk
        echo 'CONFIG_PACKAGE_opennds=m' >> .config
        echo 'CONFIG_LIBMICROHTTPD_NO_SSL=y' >> .config
        make defconfig

    - name: Compile openNDS only
      run: |
        cd openwrt-sdk
        make package/opennds/compile V=s

    - name: Upload IPK artifact
      uses: actions/upload-artifact@v4
      with:
        name: opennds-ipk
        path: openwrt-sdk/bin/packages/x86_64/base/opennds*.ipk
