name: Build openNDS no-SSL x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/openwrt/sdk:x86_64-openwrt-24.10.1

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential python3 unzip gawk wget git subversion libncurses-dev zlib1g-dev

    - name: Clone feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy openNDS package
      run: |
        mkdir -p package/network/services/opennds
        cp -r opennds/* package/network/services/opennds/

    - name: Add default config
      run: |
        mkdir -p package/network/services/opennds/files/etc/uci-defaults
        cp files/etc/uci-defaults/99-opennds-default package/network/services/opennds/files/etc/uci-defaults/

    - name: Update configuration
      run: |
        make defconfig
        echo "CONFIG_PACKAGE_opennds=m" >> .config
        echo "CONFIG_LIBMICROHTTPD_NO_SSL=y" >> .config
        make defconfig

    - name: Build openNDS only
      run: |
        make package/opennds/compile V=s

    - name: Upload .ipk artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opennds-ipk
        path: bin/packages/x86_64/base/opennds*.ipk
