name: Build openNDS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils \
            rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/24.05.0/targets/x86/64/openwrt-sdk-24.05.0-x86-64_gcc-13.2.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk

      - name: Prepare build
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/opennds/compile V=s

      - name: Upload .ipk
        uses: actions/upload-artifact@v3
        with:
          name: opennds-ipk
          path: sdk/bin/packages/x86_64/base/opennds_*.ipk
